# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/glauco/Desktop/GBEmulador

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/glauco/Desktop/GBEmulador

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/glauco/Desktop/GBEmulador/CMakeFiles /home/glauco/Desktop/GBEmulador//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/glauco/Desktop/GBEmulador/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GBEmu

# Build rule for target.
GBEmu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GBEmu
.PHONY : GBEmu

# fast build rule for target.
GBEmu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/build
.PHONY : GBEmu/fast

src/defs/CPU/CPU.o: src/defs/CPU/CPU.cpp.o
.PHONY : src/defs/CPU/CPU.o

# target to build an object file
src/defs/CPU/CPU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/CPU/CPU.cpp.o
.PHONY : src/defs/CPU/CPU.cpp.o

src/defs/CPU/CPU.i: src/defs/CPU/CPU.cpp.i
.PHONY : src/defs/CPU/CPU.i

# target to preprocess a source file
src/defs/CPU/CPU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/CPU/CPU.cpp.i
.PHONY : src/defs/CPU/CPU.cpp.i

src/defs/CPU/CPU.s: src/defs/CPU/CPU.cpp.s
.PHONY : src/defs/CPU/CPU.s

# target to generate assembly for a file
src/defs/CPU/CPU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/CPU/CPU.cpp.s
.PHONY : src/defs/CPU/CPU.cpp.s

src/defs/CPU/InstructionResolver.o: src/defs/CPU/InstructionResolver.cpp.o
.PHONY : src/defs/CPU/InstructionResolver.o

# target to build an object file
src/defs/CPU/InstructionResolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/CPU/InstructionResolver.cpp.o
.PHONY : src/defs/CPU/InstructionResolver.cpp.o

src/defs/CPU/InstructionResolver.i: src/defs/CPU/InstructionResolver.cpp.i
.PHONY : src/defs/CPU/InstructionResolver.i

# target to preprocess a source file
src/defs/CPU/InstructionResolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/CPU/InstructionResolver.cpp.i
.PHONY : src/defs/CPU/InstructionResolver.cpp.i

src/defs/CPU/InstructionResolver.s: src/defs/CPU/InstructionResolver.cpp.s
.PHONY : src/defs/CPU/InstructionResolver.s

# target to generate assembly for a file
src/defs/CPU/InstructionResolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/CPU/InstructionResolver.cpp.s
.PHONY : src/defs/CPU/InstructionResolver.cpp.s

src/defs/CPU/Instructions.o: src/defs/CPU/Instructions.cpp.o
.PHONY : src/defs/CPU/Instructions.o

# target to build an object file
src/defs/CPU/Instructions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/CPU/Instructions.cpp.o
.PHONY : src/defs/CPU/Instructions.cpp.o

src/defs/CPU/Instructions.i: src/defs/CPU/Instructions.cpp.i
.PHONY : src/defs/CPU/Instructions.i

# target to preprocess a source file
src/defs/CPU/Instructions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/CPU/Instructions.cpp.i
.PHONY : src/defs/CPU/Instructions.cpp.i

src/defs/CPU/Instructions.s: src/defs/CPU/Instructions.cpp.s
.PHONY : src/defs/CPU/Instructions.s

# target to generate assembly for a file
src/defs/CPU/Instructions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/CPU/Instructions.cpp.s
.PHONY : src/defs/CPU/Instructions.cpp.s

src/defs/Memoria/BANK00.o: src/defs/Memoria/BANK00.cpp.o
.PHONY : src/defs/Memoria/BANK00.o

# target to build an object file
src/defs/Memoria/BANK00.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/Memoria/BANK00.cpp.o
.PHONY : src/defs/Memoria/BANK00.cpp.o

src/defs/Memoria/BANK00.i: src/defs/Memoria/BANK00.cpp.i
.PHONY : src/defs/Memoria/BANK00.i

# target to preprocess a source file
src/defs/Memoria/BANK00.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/Memoria/BANK00.cpp.i
.PHONY : src/defs/Memoria/BANK00.cpp.i

src/defs/Memoria/BANK00.s: src/defs/Memoria/BANK00.cpp.s
.PHONY : src/defs/Memoria/BANK00.s

# target to generate assembly for a file
src/defs/Memoria/BANK00.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/Memoria/BANK00.cpp.s
.PHONY : src/defs/Memoria/BANK00.cpp.s

src/defs/Memoria/Memory.o: src/defs/Memoria/Memory.cpp.o
.PHONY : src/defs/Memoria/Memory.o

# target to build an object file
src/defs/Memoria/Memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/Memoria/Memory.cpp.o
.PHONY : src/defs/Memoria/Memory.cpp.o

src/defs/Memoria/Memory.i: src/defs/Memoria/Memory.cpp.i
.PHONY : src/defs/Memoria/Memory.i

# target to preprocess a source file
src/defs/Memoria/Memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/Memoria/Memory.cpp.i
.PHONY : src/defs/Memoria/Memory.cpp.i

src/defs/Memoria/Memory.s: src/defs/Memoria/Memory.cpp.s
.PHONY : src/defs/Memoria/Memory.s

# target to generate assembly for a file
src/defs/Memoria/Memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/Memoria/Memory.cpp.s
.PHONY : src/defs/Memoria/Memory.cpp.s

src/defs/Memoria/MemoryParts.o: src/defs/Memoria/MemoryParts.cpp.o
.PHONY : src/defs/Memoria/MemoryParts.o

# target to build an object file
src/defs/Memoria/MemoryParts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/Memoria/MemoryParts.cpp.o
.PHONY : src/defs/Memoria/MemoryParts.cpp.o

src/defs/Memoria/MemoryParts.i: src/defs/Memoria/MemoryParts.cpp.i
.PHONY : src/defs/Memoria/MemoryParts.i

# target to preprocess a source file
src/defs/Memoria/MemoryParts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/Memoria/MemoryParts.cpp.i
.PHONY : src/defs/Memoria/MemoryParts.cpp.i

src/defs/Memoria/MemoryParts.s: src/defs/Memoria/MemoryParts.cpp.s
.PHONY : src/defs/Memoria/MemoryParts.s

# target to generate assembly for a file
src/defs/Memoria/MemoryParts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/Memoria/MemoryParts.cpp.s
.PHONY : src/defs/Memoria/MemoryParts.cpp.s

src/defs/ROM/ROMLoader.o: src/defs/ROM/ROMLoader.cpp.o
.PHONY : src/defs/ROM/ROMLoader.o

# target to build an object file
src/defs/ROM/ROMLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/ROM/ROMLoader.cpp.o
.PHONY : src/defs/ROM/ROMLoader.cpp.o

src/defs/ROM/ROMLoader.i: src/defs/ROM/ROMLoader.cpp.i
.PHONY : src/defs/ROM/ROMLoader.i

# target to preprocess a source file
src/defs/ROM/ROMLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/ROM/ROMLoader.cpp.i
.PHONY : src/defs/ROM/ROMLoader.cpp.i

src/defs/ROM/ROMLoader.s: src/defs/ROM/ROMLoader.cpp.s
.PHONY : src/defs/ROM/ROMLoader.s

# target to generate assembly for a file
src/defs/ROM/ROMLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/defs/ROM/ROMLoader.cpp.s
.PHONY : src/defs/ROM/ROMLoader.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GBEmu.dir/build.make CMakeFiles/GBEmu.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GBEmu"
	@echo "... src/defs/CPU/CPU.o"
	@echo "... src/defs/CPU/CPU.i"
	@echo "... src/defs/CPU/CPU.s"
	@echo "... src/defs/CPU/InstructionResolver.o"
	@echo "... src/defs/CPU/InstructionResolver.i"
	@echo "... src/defs/CPU/InstructionResolver.s"
	@echo "... src/defs/CPU/Instructions.o"
	@echo "... src/defs/CPU/Instructions.i"
	@echo "... src/defs/CPU/Instructions.s"
	@echo "... src/defs/Memoria/BANK00.o"
	@echo "... src/defs/Memoria/BANK00.i"
	@echo "... src/defs/Memoria/BANK00.s"
	@echo "... src/defs/Memoria/Memory.o"
	@echo "... src/defs/Memoria/Memory.i"
	@echo "... src/defs/Memoria/Memory.s"
	@echo "... src/defs/Memoria/MemoryParts.o"
	@echo "... src/defs/Memoria/MemoryParts.i"
	@echo "... src/defs/Memoria/MemoryParts.s"
	@echo "... src/defs/ROM/ROMLoader.o"
	@echo "... src/defs/ROM/ROMLoader.i"
	@echo "... src/defs/ROM/ROMLoader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

